### ISSUE TITLE
[Request] - Prevent the bot from triggering when it doesn't recognize a command

### ISSUE THREAD

**Issue by OlioDiPalmas** [unified-ban/Terminal#66]
**Is your feature request related to a problem? Please describe.**
Prevent the bot from triggering when it doesn't recognize a command. For example, when sending the /quote command, unified/ban must not unnecessarily send the message "Invalid command!"

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pietrodicaprio** [comment]
This warn is disabled by default in stable release. Probably has been left enabled in the beta channel.\
It is now disabled.
